### PR TITLE
Added XLF format exporter

### PR DESCRIPTION
**Pull request by fabienwarniez**

### CODE REVIEW

**Comment by umpirsky** [comment]
Thanks for your PR @fabienwarniez! :+1: 

Did you try to run it? Can you post example output?

**Comment by fabienwarniez** [comment]
I did run it for all locales as part of the country list bundle.

I will post an example output in a couple of hours.

**Comment by fabienwarniez** [comment]
Here is one: https://gist.github.com/fabienwarniez/19ca88321a09580271f4

I ran the script for all locales, I can commit them, but I didn't feel it was right to commit the new data until the country-list project is using the new version of the list generator.

**Comment by umpirsky** [comment]
@fabienwarniez I expected this format:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
    <file source-language="en" target-language=".." datatype="plaintext">
        <body>
            <trans-unit id="iso-code">
                <source><![CDATA[...]]</source>
                <target><![CDATA[...]]</target>
            </trans-unit>
```

See http://www.oasis-open.org/committees/xliff/documents/xliff-specification.htm

**Comment by fabienwarniez** [comment]
@umpirsky I updated the PR to make the output XLIFF compliant. I didn't realize that Symfony is not as strict as the XLF standard. I updated the gist with the new output: https://gist.github.com/fabienwarniez/19ca88321a09580271f4

Also, CDATA is not actually required for the content of the target, so I left as is

**Comment by umpirsky** [comment]
@fabienwarniez In

``` xml
<trans-unit id="country.AF" resname="country.AF">
    <source />
    <target>Afghanistan</target>
</trans-unit>
```

Do we need resname?
Why the source is empty?

I think CDATA is requred because of names like `Côte d’Ivoire`, see https://github.com/umpirsky/country-list/blob/master/data/en/country.csv#L59.

**Comment by fabienwarniez** [comment]
`resname` is required by Symfony, this is the key that is used to look up translations from the templates / code. The `id` is just a unique identifier for that translation in the file. It is required, the id could be a hash of the resname, or it could be a random id, or it can be the same as the resname. Let me know if you want to change it, but I don't think it really matters.

There is no `source`, unless we use the English version as the source, but then we would need to make changes to the format of the data passed to the exporter, and also it would make the output files significantly bigger, for no benefit, not to mention extremely not DRY. The tag is required, but it can be empty. So I left it empty.

Lastly, special characters are HTML encoded, which is OK by XLIFF and Symfony standards:

```
<target>C&#xF4;te d&#x2019;Ivoire</target>
```

**Comment by umpirsky** [comment]
@fabienwarniez OK, let's merge it! :+1: 

Thanks!

**Comment by fabienwarniez** [comment]
Thanks! Could you release the bundle so I can start working on the country list bundle?

**Comment by umpirsky** [comment]
@fabienwarniez Sure, https://github.com/umpirsky/list-generator/releases/tag/v1.1.1

**Pull request merged**
