### PR TITLE
allow php8 and more recent symfony components

### PR DESCRIPTION
**Pull request by tacman**
Bumped the minimum version of PHP to 7.3, and also allows PHP8.

Additionally, symfony components are no longer locked to a specific version, which will allow the current version (Symfony 5), and should also allow Symfony 6.

Some errors that phpstan reported were also fixed.

### CODE REVIEW

**Review by umpirsky — APPROVED** [review]
This is sweet! Please resolve conflicts, thanks!

**Review by umpirsky — APPROVED** [review]
Thanks!

**Comment by grzesw** [comment]
@umpirsky would it be possible to tag latest changes? :)

**Comment by umpirsky** [comment]
Done `v1.2.2`. :rocket:

**Pull request merged**
